
### map

# Create a new container, each new element is generated by map relation from the original one


## Method_#1: loop
array_demo = [*1..10]

# map relation: y = x + 1
array_output = Array.new

array_demo.each do | x |
    array_output.push( x + 1 )
end

# [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
puts array_output.inspect



## Method_#2: map

# map relation: y = x + 1
map_output = array_demo.map{ |x| (x+1) }

# [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
puts map_output.inspect
